/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.panal;

import Code.Medicine;

/**
 *
 * @author N A G Y
 */
public class Update_DeleteMedicines extends javax.swing.JPanel {

    /**
     * Creates new form Update_DeleteMedicines
     */
    public Update_DeleteMedicines() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jTextFieldid = new javax.swing.JTextField();
        jTextFieldprice = new javax.swing.JTextField();
        jTextFieldquant = new javax.swing.JTextField();
        jLabelname = new javax.swing.JLabel();
        jLabelid = new javax.swing.JLabel();
        jLabelprice = new javax.swing.JLabel();
        jLabelquant = new javax.swing.JLabel();
        jTextFieldname = new javax.swing.JTextField();
        jLabelcomment = new javax.swing.JLabel();

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jTextFieldquant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldquantActionPerformed(evt);
            }
        });

        jLabelname.setText("Name");

        jLabelid.setText("ID");

        jLabelprice.setText("Price");

        jLabelquant.setText("Quantity");

        jLabelcomment.setText("Write Medicine ID get all info ...       before Update or Delete ...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabelcomment, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(132, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(241, 241, 241)
                                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldSearch)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelprice)
                    .addComponent(jLabelquant)
                    .addComponent(jLabelname)
                    .addComponent(jLabelid))
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldprice)
                        .addComponent(jTextFieldquant, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelcomment)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelname)
                        .addGap(48, 48, 48)
                        .addComponent(jLabelid)
                        .addGap(52, 52, 52)
                        .addComponent(jLabelprice)
                        .addGap(47, 47, 47)
                        .addComponent(jLabelquant))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jTextFieldprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jTextFieldquant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonUpdate))
                .addGap(72, 72, 72))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        if (!jTextFieldSearch.getText().equals("")) {
            Medicine x = new Medicine();
            Medicine returned = x.searchMedicineById(Integer.parseInt(jTextFieldSearch.getText()));
            if (returned.getMId()> 0) {
                setPanelData(returned);
            } else {
                jLabelcomment.setForeground(java.awt.Color.red);
                jLabelcomment.setText("Not Found ...!");
                resetPanelData();
            }
        } else {
            jLabelcomment.setForeground(java.awt.Color.red);
            jLabelcomment.setText("Missing required Fields ... !  Please, Search By ID before submit ...!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
      
        if (!jTextFieldname.getText().equals("") && !jTextFieldid.getText().equals("") && !jTextFieldprice.getText().equals("") && !jTextFieldquant.getText().equals("")) {
            Medicine x = new Medicine();
            x.setMId(Integer.parseInt(jTextFieldid.getText()));
            x.setMName(jTextFieldname.getText());
            x.setPrice(Integer.parseInt(jTextFieldprice.getText()));
            x.setQuant(Integer.parseInt(jTextFieldquant.getText()));
     
            if (x.updateMedicine()){
                   jLabelcomment.setForeground(java.awt.Color.red);
                   jLabelcomment.setText("Updated Successfully ... ");
            resetPanelData();
            }else{
                  jLabelcomment.setForeground(java.awt.Color.red);
                  jLabelcomment.setText("Failed to Update ... ");}
            }
        else{
        jLabelcomment.setForeground(java.awt.Color.red);
        jLabelcomment.setText("Missing required Fields ...   Please, complete them before submit ...");
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
     
        if (!jTextFieldSearch.getText().equals("")){
            Medicine x =new Medicine();
            if (x.deleteMedicine(Integer.parseInt(jTextFieldSearch.getText()))){
                
                 jLabelcomment.setForeground(java.awt.Color.red);
                 jLabelcomment.setText("Deleted Successfully ... ");
                   resetPanelData();
            } else {
                  jLabelcomment.setForeground(java.awt.Color.red);
                  jLabelcomment.setText("Failed to Delete ... ");
        }  
        } else {
                  jLabelcomment.setForeground(java.awt.Color.red);
                  jLabelcomment.setText("Missing required Fields ...   Please, complete them before submit ...");
        }   
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTextFieldquantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldquantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldquantActionPerformed
    
protected void resetPanelData(){

        jTextFieldname.setText("");
        jTextFieldid.setText("");
        jTextFieldprice.setText("");
        jTextFieldquant.setText("");
}
protected void setPanelData(Medicine x){

        jTextFieldname.setText(""+x.getMName());
        jTextFieldid.setText(""+x.getMId());
        jTextFieldprice.setText(""+x.getPrice());
        jTextFieldquant.setText(""+x.getQuant());
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelcomment;
    private javax.swing.JLabel jLabelid;
    private javax.swing.JLabel jLabelname;
    private javax.swing.JLabel jLabelprice;
    private javax.swing.JLabel jLabelquant;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldname;
    private javax.swing.JTextField jTextFieldprice;
    private javax.swing.JTextField jTextFieldquant;
    // End of variables declaration//GEN-END:variables
}
